### ISSUE TITLE
Send update to watch from app broken again

### ISSUE THREAD

**Issue by aberja** [made2k/SunriseFasting#31]
It appears the last major updates from Apple broke the send update to watch from app that you fixed in Pull Request #29 . As a result, I must open the watch app in order to see the updates made by the companion phone app.

**Comment by made2k** [comment]
Thanks, I'll try to take a look and see what's going on with this.

**Comment by made2k** [comment]
Unfortunately this looks like an issue with iOS / WatchOS. I dug in to see why the update isn't being sent and its because WatchKit is telling the application that the complication is not enabled and that there are no more transfers available to send to the complication. So the app never tries.

The code itself is [here](https://github.com/made2k/SunriseFasting/blob/a9fda24bbbf41504a0f6718f1b9dd6d5c9c0ce62/Fasting/Watch/WatchDataProvider.swift#L129). What happens is the watch `session` is active, but `session.isComplicationEnabled` returns false and `session.remainingComplicationUserInfoTransfers` returns 0. Due to this, we have to schedule the transfer of updated information instead of sending right away. This then requires either an open of the app, or a remove and re-add of the complication.

I found a few issues reported about this of others seeing the same behavior [(1)](https://stackoverflow.com/questions/71524011/wcsession-iscomplicationenabled-always-returns-false-since-ios-15-4) [(2)](https://openradar.appspot.com/FB9946393). I also created a demo project that reproduces the issue and sent that to Apple. I will be able to provide updates here if I hear back. 

Since this appears currently to be an issue that I cannot fix via code, I'm going to close for now and will be able to provide updates if I hear back from Apple, or if new versions of iOS / WatchOS fix this.

**Comment by made2k** [comment]
I tested this again with the new updates using iOS 15.5 and WatchOS 8.6 and this issue seems to be resolved.

**Comment by aberja** [comment]
Unfortunately, this is still not working for me.  After I update the app to close a fast, the watch app shows that I am still in a fast.  I have to click on the complication for the watch app to update.  I'm running v 8.6(19T572) and 15.5 on the iPhone 11.

**Comment by aberja** [comment]
FYI, I started a fast this evening in the app and the watch app complication automatically updated.  I then stopped the fast in the app and the watch app automatically updated.  So I don't know why it didn't work for me this morning.  But it worked this evening.  I'll let you know if I have any other issue with this.
